import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import menuRouter from "./menu";
import ordersRouter from "./orders";
import reservationsRouter from "./reservations";
import dashboardRouter from "./dashboard";
import eventsRouter from "./events";
import walkInsRouter from "./walk-ins";
import tableReservationsRouter from "./table-reservations";
import paymentsRouter from "./payments";
import refundsRouter from "./refunds";
import salesReportsRouter from "./sales-reports";
import auditLogsRouter from "./audit-logs";
import feedbackRouter from "./feedback";
import adminRouter from "./admin";
import archiveRouter from "./archive";
import maintenanceRouter from "./maintenance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(menuRouter);
router.use(ordersRouter);
router.use(reservationsRouter);
router.use(dashboardRouter);
router.use(eventsRouter);
router.use(walkInsRouter);
router.use(tableReservationsRouter);
router.use(paymentsRouter);
router.use(refundsRouter);
router.use(salesReportsRouter);
router.use(auditLogsRouter);
router.use(feedbackRouter);
router.use(adminRouter);
router.use(archiveRouter);
router.use(maintenanceRouter);

export default router;
